# Generated by Django 5.1.3 on 2024-12-08 00:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publish', '0002_alter_imagen_url_imagen'),
    ]

    operations = [
        migrations.RenameField(
            model_name='imagen',
            old_name='url_imagen',
            new_name='imagen',
        ),
    ]
