# Generated by Django 5.1.3 on 2025-01-07 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publish', '0003_rename_url_imagen_imagen_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='zona',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
