# Generated by Django 5.1.3 on 2025-02-01 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publish', '0006_producto_venta_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='venta_estado',
            field=models.CharField(choices=[('EnVenta', 'En venta'), ('Vendido', 'Vendido')], default='EnVenta', max_length=20),
        ),
    ]
