# Generated by Django 5.1.3 on 2024-11-20 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0002_usuario'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='sector',
            table='sector',
        ),
        migrations.AlterModelTable(
            name='usuario',
            table='usuario',
        ),
    ]
