# Generated by Django 5.1.3 on 2024-11-23 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0004_usuario_email_alter_usuario_cedula_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='email',
            field=models.EmailField(max_length=254, null=True, unique=True),
        ),
    ]
