# Generated by Django 5.1.3 on 2025-01-26 21:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0010_alter_usuario_birth_date_alter_usuario_sector'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='birth_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='sector',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='signup.sector'),
        ),
    ]
