# Generated by Django 5.1.3 on 2025-01-28 00:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_alter_chatmessage_options_chat_participants_and_more'),
        ('publish', '0005_rename_zona_producto_sector'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='producto',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='chats', to='publish.producto'),
        ),
    ]
