# Generated by Django 5.1.3 on 2025-01-28 00:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_chat_producto'),
        ('publish', '0005_rename_zona_producto_sector'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chats', to='publish.producto'),
        ),
    ]
