# Generated by Django 5.1.3 on 2024-12-07 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publish', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagen',
            name='url_imagen',
            field=models.ImageField(upload_to='imagenes_producto/'),
        ),
    ]
