# Generated by Django 5.1.3 on 2025-01-07 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publish', '0004_producto_zona'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto',
            old_name='zona',
            new_name='sector',
        ),
    ]
