# Generated by Django 5.1.3 on 2025-02-01 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publish', '0005_rename_zona_producto_sector'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='venta_estado',
            field=models.CharField(choices=[('EnVenta', 'En venta'), ('Vendido', 'Vendido'), ('Reservado', 'Reservado')], default='EnVenta', max_length=20),
        ),
    ]
