# Generated by Django 5.1.3 on 2025-01-26 21:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0009_alter_usuario_birth_date_alter_usuario_sector'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='birth_date',
            field=models.DateField(blank=True, null=True, default='2000-01-01'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='sector',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='signup.sector'),
        ),
    ]
